server:
  port: 9006
mybatis-plus:
  type-aliases-package: com.binbini.imall.pojo
  configuration:
    map-underscore-to-camel-case: false
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration-properties: classpath:mybatis/mybatis-config.xml
spring:
  application:
    name: imall-provide-search
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-7xvah021798y6e1dd4o.mysql.rds.aliyuncs.com:3306/imall?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    username: binbini
    password: Chang687501
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 120.78.157.152
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      #单机
      defaultZone: http://120.78.157.152:7001/eureka/
      #集群
#      defaultZone: http://studio.eureka7001.com:7001/eureka/,http://studio.eureka7002.com:7002/eureka/,http://studio.eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 8.134.94.102
    instance-id: imall-provide-search-9006
info:
  app.name: binbini-iMall
  company.name: binbini.com
es:
  connect.ip: 120.78.157.152
  node.client.port: 9200
item:
  index: item
  type: itemList