server:
  port: 9006
mybatis-plus:
  type-aliases-package: com.binbini.imall.pojo
  configuration:
    map-underscore-to-camel-case: false
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration-properties: classpath:mybatis/mybatis-config.xml
spring:
  application:
    name: imall-provide-search
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iMall?useUnicode=true&characterEncoding=utf8&serverTimezone=CTT
    username: root
    password: Chang687501
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client:
    service-url:
      #单机
      #      defaultZone: http://localhost:7001/eureka/
      #集群
      defaultZone: http://binbini.eureka7001.com:7001/eureka/,http://binbini.eureka7002.com:7002/eureka/,http://binbini.eureka7003.com:7003/eureka/
  instance:
    instance-id: imall-provide-search-9006
info:
  app.name: binbini-iMall
  company.name: binbini.com
es:
  connect.ip: 127.0.0.1
  node.client.port: 9200
item:
  index: item
  type: itemList